
window.majors = [
    { id: 1, name: "Accountancy (BS)", field: "Business", college: "W. P. Carey School of Business", salary: "$62,000" },
    { id: 2, name: "Agribusiness Innovation and Technology (BA)", field: "Business", college: "W. P. Carey School of Business", salary: "$62,000" },
    { id: 3, name: "Applied Business and Technology Solutions (BA)", field: "Business", college: "W. P. Carey School of Business", salary: "$62,000" },
    { id: 4, name: "Artificial Intelligence in Business (BS)", field: "Business/Technology", college: "W. P. Carey School of Business", salary: "$75,000" },
    { id: 5, name: "Business Administration (BA)", field: "Business", college: "W. P. Carey School of Business", salary: "$62,000" },
    { id: 6, name: "Business Data Analytics (BS)", field: "Business/Technology", college: "W. P. Carey School of Business", salary: "$62,000" },
    { id: 7, name: "Business Entrepreneurship (BS)", field: "Business/Entrepreneurship", college: "W. P. Carey School of Business", salary: "$60,000" },
    { id: 8, name: "Communication (BA)", field: "Communications", college: "W. P. Carey / CLA S (varies)", salary: "$40,000" },
    { id: 9, name: "Computer Information Systems (BS)", field: "Business/Technology", college: "W. P. Carey School of Business", salary: "$62,000" },
    { id: 10, name: "Corporate Accounting (BA)", field: "Business", college: "W. P. Carey School of Business", salary: "$62,000" },
    { id: 11, name: "Economics (BS)", field: "Business/Economics", college: "W. P. Carey School of Business", salary: "$62,000" },
    { id: 12, name: "Entrepreneurial Leadership (BA)", field: "Business/Leadership", college: "W. P. Carey School of Business", salary: "$60,000" },
    { id: 13, name: "Finance (BS)", field: "Business/Finance", college: "W. P. Carey School of Business", salary: "$62,000" },
    { id: 14, name: "Financial Planning (BA)", field: "Business/Finance", college: "W. P. Carey School of Business", salary: "$62,000" },
    { id: 15, name: "Financial Technology (BS)", field: "Business/Technology", college: "W. P. Carey School of Business", salary: "$75,000" },
    { id: 16, name: "Food Industry Management (BA)", field: "Business/Food Systems", college: "W. P. Carey School of Business", salary: "$50,000" },
    { id: 17, name: "Global Leadership (BA)", field: "Business/International", college: "W. P. Carey School of Business", salary: "$62,000" },
    { id: 18, name: "Global Logistics Management (BA)", field: "Business/Logistics", college: "W. P. Carey School of Business", salary: "$62,000" },
    { id: 19, name: "Global Politics (BA)", field: "International/Politics", college: "W. P. Carey / School of Politics & Global Studies (varies)", salary: "$50,000" },
    { id: 20, name: "Health Care (BA)", field: "Business/Health", college: "W. P. Carey School of Business", salary: "$59,000" },
    { id: 21, name: "Human Resources (BA)", field: "Business/Management", college: "W. P. Carey School of Business", salary: "$62,000" },
    { id: 22, name: "Information Security (BA)", field: "Business/Technology", college: "W. P. Carey School of Business", salary: "$75,000" },
    { id: 23, name: "Language and Culture (BA)", field: "Humanities/Languages", college: "W. P. Carey / CLA S (varies)", salary: "$50,000" },
    { id: 24, name: "Law (BA)", field: "Business/Legal", college: "W. P. Carey School of Business", salary: "$65,000" },
    { id: 25, name: "Management (BS)", field: "Business/Management", college: "W. P. Carey School of Business", salary: "$62,000" },
    { id: 26, name: "Marketing (BS)", field: "Business/Marketing", college: "W. P. Carey School of Business", salary: "$62,000" },
    { id: 27, name: "Marketing (Digital) (BS)", field: "Business/Marketing", college: "W. P. Carey School of Business", salary: "$62,000" },
    { id: 28, name: "Marketing (Professional Sales) (BS)", field: "Business/Marketing", college: "W. P. Carey School of Business", salary: "$62,000" },
    { id: 29, name: "Public Service and Public Policy (BA)", field: "Public Policy", college: "W. P. Carey School of Business", salary: "$50,000" },
    { id: 30, name: "Real Estate and Applied Finance (BS)", field: "Business/Real Estate", college: "W. P. Carey School of Business", salary: "$62,000" },
    { id: 31, name: "Retail Management (BA)", field: "Business/Retail", college: "W. P. Carey School of Business", salary: "$50,000" },
    { id: 32, name: "Sports Business (BA)", field: "Business/Sports", college: "W. P. Carey School of Business", salary: "$50,000" },
    { id: 33, name: "Statistics (BA)", field: "Analytics/Math", college: "W. P. Carey School of Business", salary: "$75,000" },
    { id: 34, name: "Supply Chain Management (BS)", field: "Business/Logistics", college: "W. P. Carey School of Business", salary: "$62,000" },
    { id: 35, name: "Sustainability (BA)", field: "Environmental/Business", college: "W. P. Carey School of Business / Wrigley (varies)", salary: "$62,000" },
    { id: 36, name: "Technology (BA)", field: "Business/Technology", college: "W. P. Carey School of Business", salary: "$75,000" },
    { id: 37, name: "Tourism (BA)", field: "Business/Tourism", college: "W. P. Carey School of Business", salary: "$50,000" },
    { id: 38, name: "Biomedical Engineering (BSE)", field: "Engineering/Health", college: "Ira A. Fulton Schools of Engineering", salary: "$76,000" },
    { id: 39, name: "Computer Science (BA)", field: "Computer Science", college: "College of Liberal Arts and Sciences", salary: "$95,000" },
    { id: 40, name: "Computer Science (BS)", field: "Computer Science", college: "Ira A. Fulton Schools of Engineering", salary: "$95,000" },
    { id: 41, name: "Computer Systems Engineering (BSE)", field: "Engineering", college: "Ira A. Fulton Schools of Engineering", salary: "$76,000" },
    { id: 42, name: "Electrical Engineering (BSE)", field: "Engineering", college: "Ira A. Fulton Schools of Engineering", salary: "$76,000" },
    { id: 43, name: "Aerospace Engineering (BSE)", field: "Engineering/Aerospace", college: "Ira A. Fulton Schools of Engineering", salary: "$76,000" },
    { id: 44, name: "Chemical Engineering (BSE)", field: "Engineering", college: "Ira A. Fulton Schools of Engineering", salary: "$76,000" },
    { id: 45, name: "Civil Engineering (BSE)", field: "Engineering", college: "Ira A. Fulton Schools of Engineering", salary: "$76,000" },
    { id: 46, name: "Construction Engineering (BSE)", field: "Engineering/Construction", college: "Ira A. Fulton Schools of Engineering", salary: "$76,000" },
    { id: 47, name: "Construction Management and Technology (BS)", field: "Engineering/Construction", college: "Ira A. Fulton Schools of Engineering", salary: "$70,000" },
    { id: 48, name: "Environmental Engineering (BSE)", field: "Engineering/Environmental", college: "Ira A. Fulton Schools of Engineering", salary: "$76,000" },
    { id: 49, name: "Mechanical Engineering (BSE)", field: "Engineering", college: "Ira A. Fulton Schools of Engineering", salary: "$76,000" },
    { id: 50, name: "Materials Science and Engineering (BSE)", field: "Engineering/Materials", college: "Ira A. Fulton Schools of Engineering", salary: "$76,000" },
    { id: 51, name: "Industrial Engineering (BSE)", field: "Engineering", college: "Ira A. Fulton Schools of Engineering", salary: "$76,000" },
    { id: 52, name: "Software Engineering (BS)", field: "Engineering/Computer", college: "Ira A. Fulton Schools of Engineering", salary: "$95,000" },
    { id: 53, name: "Manufacturing Engineering (BS)", field: "Engineering", college: "Ira A. Fulton Schools of Engineering", salary: "$76,000" },
    { id: 54, name: "Engineering Science (Business) (BS)", field: "Engineering/Interdisciplinary", college: "Ira A. Fulton Schools of Engineering", salary: "$76,000" },
    { id: 55, name: "Engineering Science (Microelectronics) (BS)", field: "Engineering/Interdisciplinary", college: "Ira A. Fulton Schools of Engineering", salary: "$76,000" },
    { id: 56, name: "Engineering Management (BSE)", field: "Engineering/Management", college: "Ira A. Fulton Schools of Engineering", salary: "$76,000" },
    { id: 57, name: "Energy and Mechanical Engineering (BSE)", field: "Engineering", college: "Ira A. Fulton Schools of Engineering", salary: "$76,000" },
    { id: 58, name: "Computer Science (Software Engineering) (BS)", field: "Engineering/Computer", college: "Ira A. Fulton Schools of Engineering", salary: "$95,000" },
    { id: 59, name: "Electrical Engineering (Electric Power & Energy) (BSE)", field: "Engineering", college: "Ira A. Fulton Schools of Engineering", salary: "$76,000" },
    { id: 60, name: "Aeronautical Management Technology (Aviation) (BS)", field: "Engineering/Aviation", college: "Ira A. Fulton Schools of Engineering", salary: "$70,000" },
    { id: 61, name: "Astronomical and Planetary Sciences (BS)", field: "Science/Astronomy", college: "School of Earth and Space Exploration (CLAS)", salary: "$40,000" },
    { id: 62, name: "Earth and Environmental Sciences (BA)", field: "Science/Environmental", college: "School of Earth and Space Exploration (CLAS)", salary: "$40,000" },
    { id: 63, name: "Earth and Environmental Sciences (BS)", field: "Science/Environmental", college: "School of Earth and Space Exploration (CLAS)", salary: "$40,000" },
    { id: 64, name: "Astrophysics (BS)", field: "Science/Physics", college: "School of Earth and Space Exploration (CLAS)", salary: "$76,000" },
    { id: 65, name: "Earth and Space Exploration (BS)", field: "Science/Earth", college: "School of Earth and Space Exploration (CLAS)", salary: "$40,000" },
    { id: 66, name: "Earth and Space Exploration: Astrobiology (BS)", field: "Science/Interdisciplinary", college: "School of Earth and Space Exploration (CLAS)", salary: "$40,000" },
    { id: 67, name: "Earth and Space Exploration: Exploration Systems Design (BS)", field: "Science/Engineering", college: "School of Earth and Space Exploration (CLAS)", salary: "$76,000" },
    { id: 68, name: "Earth and Space Exploration: Geological & Planetary Sciences (BS)", field: "Science/Geology", college: "School of Earth and Space Exploration (CLAS)", salary: "$40,000" },
    { id: 69, name: "Journalism and Mass Communication (BA)", field: "Arts/Communications", college: "Walter Cronkite School of Journalism and Mass Communication", salary: "$40,000" },
    { id: 70, name: "Sports Journalism (BA)", field: "Arts/Sports Media", college: "Walter Cronkite School of Journalism and Mass Communication", salary: "$40,000" },
    { id: 71, name: "Digital Audiences (BS)", field: "Arts/Communications", college: "Walter Cronkite School of Journalism and Mass Communication", salary: "$40,000" },
    { id: 72, name: "Mass Communication & Media Studies (BA)", field: "Arts/Communications", college: "Walter Cronkite School of Journalism and Mass Communication", salary: "$40,000" },
    { id: 73, name: "Digital Media Literacy (BA)", field: "Arts/Media Studies", college: "Walter Cronkite School of Journalism and Mass Communication", salary: "$40,000" },
    { id: 74, name: "Architectural Studies (BS Design)", field: "Design/Architecture", college: "Herberger Institute for Design and the Arts", salary: "$50,000" },
    { id: 75, name: "Art (BFA/BA, various concentrations)", field: "Arts/Fine Arts", college: "Herberger Institute for Design and the Arts", salary: "$40,000" },
    { id: 76, name: "Costume Design & Tech (BFA)", field: "Arts/Design", college: "Herberger Institute for Design and the Arts", salary: "$40,000" },
    { id: 77, name: "Dance (BFA)", field: "Arts/Performance", college: "Herberger Institute for Design and the Arts", salary: "$40,000" },
    { id: 78, name: "Dance (Education) (BFA)", field: "Arts/Education", college: "Herberger Institute for Design and the Arts", salary: "$40,000" },
    { id: 79, name: "Environmental Design (BS)", field: "Design/Environmental", college: "Herberger Institute for Design and the Arts", salary: "$50,000" },
    { id: 80, name: "Fashion (BA, various concentrations)", field: "Design/Fashion", college: "Herberger Institute for Design and the Arts", salary: "$40,000" },
    { id: 81, name: "Film (BA, Filmmaking Practices)", field: "Arts/Film", college: "Herberger Institute for Design and the Arts", salary: "$40,000" },
    { id: 82, name: "Film and Media Production (BFA)", field: "Arts/Film", college: "Herberger Institute for Design and the Arts", salary: "$40,000" },
    { id: 83, name: "Game Design (BS)", field: "Arts/Gaming", college: "Herberger Institute for Design and the Arts", salary: "$60,000" },
    { id: 84, name: "Graphic Design (BS Design)", field: "Design/Graphic Arts", college: "Herberger Institute for Design and the Arts", salary: "$40,000" },
    { id: 85, name: "Industrial Design (BS Design)", field: "Design/Industrial", college: "Herberger Institute for Design and the Arts", salary: "$50,000" },
    { id: 86, name: "Interior Design (BS Design)", field: "Design/Interior", college: "Herberger Institute for Design and the Arts", salary: "$40,000" },
    { id: 87, name: "Landscape Architecture (BS)", field: "Design/Landscaping", college: "Herberger Institute for Design and the Arts", salary: "$40,000" },
    { id: 88, name: "Media Arts & Sciences (BA, various concentrations)", field: "Interdisciplinary/Media", college: "Herberger Institute for Design and the Arts", salary: "$40,000" },
    { id: 89, name: "Media Arts & Sciences (BS, Games & Interactive Media)", field: "Interdisciplinary/Media", college: "Herberger Institute for Design and the Arts", salary: "$60,000" },
    { id: 90, name: "Music (BA/BM)", field: "Arts/Music", college: "Herberger Institute for Design and the Arts", salary: "$40,000" },
    { id: 91, name: "Music (Popular Music) (BA)", field: "Arts/Music", college: "Herberger Institute for Design and the Arts", salary: "$40,000" },
    { id: 92, name: "Music Learning & Teaching (BM)", field: "Arts/Education", college: "Herberger Institute for Design and the Arts", salary: "$40,000" },
    { id: 93, name: "Music Therapy (BM)", field: "Arts/Music Therapy", college: "Herberger Institute for Design and the Arts", salary: "$40,000" },
    { id: 94, name: "Performance (BM, various instruments/voice)", field: "Arts/Music Performance", college: "Herberger Institute for Design and the Arts", salary: "$40,000" },
    { id: 95, name: "Performance & Movement (BA)", field: "Arts/Performance", college: "Herberger Institute for Design and the Arts", salary: "$40,000" },
    { id: 96, name: "Theatre (BA)", field: "Arts/Theatre", college: "Herberger Institute for Design and the Arts", salary: "$40,000" },
    { id: 97, name: "Theatre (Design & Production) (BA)", field: "Arts/Theatre", college: "Herberger Institute for Design and the Arts", salary: "$40,000" },
    { id: 98, name: "Community Health (BS)", field: "Health/Public Health", college: "Edson College of Nursing & Health Innovation", salary: "$58,000" },
    { id: 99, name: "Health Care Compliance & Regulations (BS)", field: "Health/Administration", college: "Edson College of Nursing & Health Innovation", salary: "$58,000" },
    { id: 100, name: "Health Care Coordination (BS)", field: "Health/Administration", college: "Edson College of Nursing & Health Innovation", salary: "$58,000" },
    { id: 101, name: "Health Entrepreneurship & Innovation (BS)", field: "Health/Business", college: "Edson College of Nursing & Health Innovation", salary: "$58,000" },
    { id: 102, name: "Integrative Health (BS)", field: "Health/Interdisciplinary", college: "Edson College of Nursing & Health Innovation", salary: "$58,000" },
    { id: 103, name: "Applied Science: Health Entrepreneurship & Innovation (BAS)", field: "Health/Business", college: "Edson College of Nursing & Health Innovation", salary: "$58,000" },
    { id: 104, name: "Nursing (BSN)", field: "Health/Nursing", college: "Edson College of Nursing & Health Innovation", salary: "$58,000" },

    /* continuing list (from earlier continuation messages) */
    { id: 105, name: "Physics (BS)", field: "Science", college: "College of Liberal Arts and Sciences (School of Mathematical & Statistical Sciences)", salary: "$50,000" },
    { id: 106, name: "Political Science (BA/BS)", field: "Social Sciences", college: "School of Social and Behavioral Sciences / College of Liberal Arts and Sciences", salary: "$50,000" },
    { id: 107, name: "Psychological Science (BS)", field: "Social Sciences", college: "School of Social and Behavioral Sciences / New College of Interdisciplinary Arts & Sciences", salary: "$50,000" },
    { id: 108, name: "Psychology (BA/BS)", field: "Social Sciences", college: "School of Social and Behavioral Sciences / College of Liberal Arts and Sciences", salary: "$50,000" },
    { id: 109, name: "Public Health (BS)", field: "Health", college: "College of Health Solutions", salary: "$50,000" },
    { id: 110, name: "Public Management and Policy (BS)", field: "Public Affairs", college: "Watts College of Public Service & Community Solutions (School of Public Affairs)", salary: "$50,000" },
    { id: 111, name: "Religious Studies (BA)", field: "Humanities", college: "School of Historical, Philosophical and Religious Studies (College of Liberal Arts & Sciences)", salary: "$40,000" },
    { id: 112, name: "Retailing and Consumer Science (BS)", field: "Business", college: "W. P. Carey School of Business", salary: "" },
    { id: 113, name: "Russian (BA)", field: "Humanities/Language", college: "School of International Letters and Cultures (College of Liberal Arts & Sciences)", salary: "$48,000" },
    { id: 114, name: "Sociology (BA/BS)", field: "Social Sciences", college: "School of Social and Behavioral Sciences / New College", salary: "$50,000" },
    { id: 115, name: "Spanish (BA)", field: "Humanities/Language", college: "School of International Letters and Cultures (College of Liberal Arts & Sciences)", salary: "$50,000" },
    { id: 116, name: "Speech, Language and Hearing Sciences (BS)", field: "Health", college: "College of Health Solutions", salary: "$50,000" },
    { id: 117, name: "Statistics and Data Science (BS)", field: "Science/Technology", college: "College of Liberal Arts and Sciences (School of Mathematical & Statistical Sciences)", salary: "$70,000" },
    { id: 118, name: "Studio Art (BFA)", field: "Arts", college: "Herberger Institute for Design and the Arts (School of Art)", salary: "$40,000" },
    { id: 119, name: "Sustainable Built Environments (BS)", field: "Engineering/Technology", college: "Ira A. Fulton Schools of Engineering (School of Sustainable Engineering and the Built Environment)", salary: "$60,000" },
    { id: 120, name: "Systems (Human Systems) Engineering (BS)", field: "Engineering/Technology", college: "Ira A. Fulton Schools of Engineering (The Polytechnic School)", salary: "$60,000" },
    { id: 121, name: "Theatre Arts (BFA)", field: "Arts", college: "Herberger Institute for Design and the Arts (School of Music, Dance and Theatre)", salary: "$40,000" },
    { id: 122, name: "Theatre Production (BFA)", field: "Arts", college: "Herberger Institute for Design and the Arts (School of Music, Dance and Theatre)", salary: "$40,000" },
    { id: 123, name: "Urban and Regional Development (BS)", field: "Urban Studies", college: "Watts College of Public Service & Community Solutions (School of Community Resources & Development)", salary: "$50,000" },
    { id: 124, name: "World Literature (BA)", field: "Humanities", college: "School of International Letters and Cultures (College of Liberal Arts & Sciences)", salary: "$50,000" },

    /* items added in the longer lists (125 onward) */
    { id: 125, name: "Criminology and Criminal Justice (BS / Policing option)", field: "Law/Justice/Public Service", college: "Watts College of Public Service & Community Solutions", salary: "" },
    { id: 126, name: "Communication (BA, online)", field: "Humanities/Social Sciences", college: "College of Liberal Arts & Sciences / ASU Online", salary: "" },
    { id: 127, name: "Actuarial Science (BS)", field: "Science/Mathematics", college: "College of Liberal Arts & Sciences", salary: "" },
    { id: 128, name: "African and African American Studies (BA)", field: "Humanities/Social Sciences", college: "College of Liberal Arts & Sciences", salary: "" },
    { id: 129, name: "American Indian Studies (BS)", field: "Humanities/Social Sciences", college: "College of Liberal Arts & Sciences", salary: "" },
    { id: 130, name: "Anthropology (BA / BS)", field: "Social Sciences", college: "College of Liberal Arts & Sciences", salary: "" },
    { id: 131, name: "Applied Biological Sciences (Secondary Education in Biology) (BS)", field: "Science/Education", college: "College of Integrative Sciences & Arts (CISA)", salary: "" },
    { id: 132, name: "Applied Mathematics for Life and Social Sciences (BS)", field: "Mathematics", college: "College of Liberal Arts & Sciences", salary: "" },
    { id: 133, name: "Applied Science (Health Entrepreneurship & Innovation) (BAS)", field: "Health/Business", college: "Edson College of Nursing & Health Innovation", salary: "" },
    { id: 134, name: "Biological Sciences (BS - various tracks)", field: "Science", college: "College of Liberal Arts & Sciences", salary: "" },
    { id: 135, name: "Biochemistry (BA / BS)", field: "Science/Health", college: "College of Liberal Arts & Sciences", salary: "" },
    { id: 136, name: "Biophysics (BS)", field: "Science", college: "College of Liberal Arts & Sciences", salary: "" },
    { id: 137, name: "Chemistry (BA / BS)", field: "Science/Chemistry", college: "College of Liberal Arts & Sciences", salary: "" },
    { id: 138, name: "Civic and Economic Thought and Leadership (BA)", field: "Humanities/Social Sciences", college: "School of Civic and Economic Thought and Leadership", salary: "" },
    { id: 139, name: "Data Science (BS)", field: "Science/Technology", college: "College of Liberal Arts & Sciences", salary: "" },
    { id: 140, name: "Earth and Environmental Sciences (BA / BS)", field: "Science/Environmental", college: "School of Earth and Space Exploration (CLAS)", salary: "" },
    { id: 141, name: "Earth and Space Exploration (BS, various tracks)", field: "Science/Planetary", college: "School of Earth and Space Exploration", salary: "" },
    { id: 142, name: "English (Writing, Rhetorics and Literacies) (BA)", field: "Humanities", college: "College of Liberal Arts & Sciences", salary: "" },
    { id: 143, name: "Family and Human Development (BS)", field: "Social Sciences/Health", college: "College of Liberal Arts & Sciences", salary: "" },
    { id: 144, name: "French (BA)", field: "Humanities/Language", college: "College of Liberal Arts & Sciences", salary: "" },
    { id: 145, name: "Gender, Women and Sexuality Studies (BA)", field: "Humanities/Social Sciences", college: "College of Liberal Arts & Sciences", salary: "" },
    { id: 146, name: "Geographic Information Science (BS)", field: "Science/Technology", college: "College of Liberal Arts & Sciences", salary: "" },

    /* 147 - onward (the extended lists) */
    { id: 147, name: "Accounting", field: "Business", college: "W. P. Carey School of Business", salary: "" },
    { id: 148, name: "Aerospace Engineering", field: "Engineering", college: "Ira A. Fulton Schools of Engineering", salary: "" },
    { id: 149, name: "Apparel Design", field: "Arts", college: "Herberger Institute for Design and the Arts", salary: "" },
    { id: 150, name: "Architectural Studies", field: "Architecture & Design", college: "Herberger Institute for Design and the Arts", salary: "" },
    { id: 151, name: "Art (Studio)", field: "Arts", college: "Herberger Institute for Design and the Arts", salary: "" },
    { id: 152, name: "Astrobiology", field: "Science", college: "New College of Interdisciplinary Arts & Sciences / CLAS", salary: "" },
    { id: 153, name: "Astronomy", field: "Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 154, name: "Athletic Training", field: "Health", college: "College of Health Solutions", salary: "" },
    { id: 155, name: "Audiology & Speech Sciences", field: "Health", college: "College of Health Solutions", salary: "" },
    { id: 156, name: "Biochemistry", field: "Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 157, name: "Biological Sciences (BS)", field: "Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 158, name: "Biomedical Engineering", field: "Engineering/Health", college: "Ira A. Fulton Schools of Engineering", salary: "" },
    { id: 159, name: "Biophysics", field: "Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 160, name: "Biotechnology", field: "Science", college: "The Polytechnic School / CLA S (varies)", salary: "" },
    { id: 161, name: "Business Data Analytics", field: "Business", college: "W. P. Carey School of Business", salary: "" },
    { id: 162, name: "Business Entrepreneurship", field: "Business", college: "W. P. Carey School of Business", salary: "" },
    { id: 163, name: "Chemical Engineering", field: "Engineering", college: "Ira A. Fulton Schools of Engineering", salary: "" },
    { id: 164, name: "Chemistry", field: "Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 165, name: "Civil Engineering", field: "Engineering", college: "Ira A. Fulton Schools of Engineering", salary: "" },
    { id: 166, name: "Classics", field: "Humanities", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 167, name: "Climate Science and Solutions", field: "Environmental Science", college: "School of Sustainability / Julie Ann Wrigley", salary: "" },
    { id: 168, name: "Communication (BS)", field: "Communication", college: "Hugh Downs School of Human Communication / CLA S", salary: "" },
    { id: 169, name: "Community Planning", field: "Design", college: "Herberger Institute for Design and the Arts", salary: "" },
    { id: 170, name: "Computational Mathematics", field: "Mathematics", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 171, name: "Computer Engineering", field: "Engineering", college: "Ira A. Fulton Schools of Engineering", salary: "" },
    { id: 172, name: "Computer Science (BS)", field: "Computer Science", college: "Ira A. Fulton Schools of Engineering", salary: "" },
    { id: 173, name: "Computer Science (BA)", field: "Computer Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 174, name: "Construction Management", field: "Engineering/Construction", college: "Ira A. Fulton Schools of Engineering", salary: "" },
    { id: 175, name: "Creative Writing", field: "Arts/Humanities", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 176, name: "Criminal Justice Studies", field: "Social Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 177, name: "Criminology & Criminal Justice", field: "Social Science", college: "College of Liberal Arts and Sciences / Watts College", salary: "" },
    { id: 178, name: "Cybersecurity", field: "Computer Science/Technology", college: "Ira A. Fulton Schools of Engineering", salary: "" },
    { id: 179, name: "Data Science", field: "Data Science/Technology", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 180, name: "Earth & Space Exploration", field: "Planetary Science", college: "School of Earth and Space Exploration (CLAS)", salary: "" },
    { id: 181, name: "Ecology", field: "Biology/Environmental", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 182, name: "Economics (BS)", field: "Business/Economics", college: "W. P. Carey School of Business", salary: "" },
    { id: 183, name: "Economics (BA)", field: "Social Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 184, name: "Elementary Education", field: "Education", college: "Mary Lou Fulton Teachers College", salary: "" },
    { id: 185, name: "Engineering (General)", field: "Engineering", college: "Ira A. Fulton Schools of Engineering", salary: "" },
    { id: 186, name: "English", field: "Humanities", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 187, name: "Environmental Engineering", field: "Engineering", college: "Ira A. Fulton Schools of Engineering", salary: "" },
    { id: 188, name: "Environmental Science", field: "Science/Environmental", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 189, name: "Exercise Science", field: "Health", college: "College of Health Solutions", salary: "" },
    { id: 190, name: "Fashion and Merchandising Management", field: "Business/Design", college: "The Polytechnic School / Herberger (varies)", salary: "" },
    { id: 191, name: "Finance", field: "Business/Finance", college: "W. P. Carey School of Business", salary: "" },
    { id: 192, name: "Film and Media Studies", field: "Arts/Film", college: "College of Liberal Arts and Sciences / Herberger (varies)", salary: "" },
    { id: 193, name: "Forensic Chemistry", field: "Science/Chemistry", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 194, name: "Forensic Science", field: "Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 195, name: "Geographic Information Science", field: "Technology/GIS", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 196, name: "Geography", field: "Social Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 197, name: "Geology", field: "Earth Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 198, name: "Global Health", field: "Health", college: "College of Health Solutions", salary: "" },
    { id: 199, name: "Graphic Design", field: "Design", college: "Herberger Institute for Design and the Arts", salary: "" },
    { id: 200, name: "History", field: "Humanities", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 201, name: "Hospitality Management", field: "Business", college: "W. P. Carey School of Business", salary: "" },
    { id: 202, name: "Human Development and Family Science", field: "Social Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 203, name: "Human Biology", field: "Health/Biology", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 204, name: "Human Resources", field: "Business", college: "W. P. Carey School of Business", salary: "" },
    { id: 205, name: "Industrial Design", field: "Design", college: "Herberger Institute for Design and the Arts", salary: "" },
    { id: 206, name: "Industrial Engineering", field: "Engineering", college: "Ira A. Fulton Schools of Engineering", salary: "" },
    { id: 207, name: "Information Technology", field: "Technology", college: "W. P. Carey School of Business / Ira A. Fulton (varies)", salary: "" },
    { id: 208, name: "Integrative Biology", field: "Biology", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 209, name: "Interior Design", field: "Design", college: "Herberger Institute for Design and the Arts", salary: "" },
    { id: 210, name: "Journalism", field: "Communication/Media", college: "Walter Cronkite School of Journalism and Mass Communication", salary: "" },
    { id: 211, name: "Judaic Studies", field: "Humanities", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 212, name: "Kinesiology", field: "Health", college: "College of Health Solutions", salary: "" },
    { id: 213, name: "Landscape Architecture", field: "Design", college: "Herberger Institute for Design and the Arts", salary: "" },
    { id: 214, name: "Latin American Studies", field: "Humanities", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 215, name: "Leadership and Innovation", field: "Education/Leadership", college: "Mary Lou Fulton Teachers College", salary: "" },
    { id: 216, name: "Mechanical Engineering", field: "Engineering", college: "Ira A. Fulton Schools of Engineering", salary: "" },
    { id: 217, name: "Media and Information", field: "Communication", college: "Walter Cronkite School of Journalism and Mass Communication", salary: "" },
    { id: 218, name: "Medical Studies", field: "Health/Pre-Professional", college: "College of Health Solutions", salary: "" },
    { id: 219, name: "Meteorology", field: "Earth/Atmospheric Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 220, name: "Microbiology", field: "Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 221, name: "Mining Engineering", field: "Engineering", college: "The Polytechnic School", salary: "" },
    { id: 222, name: "Nanoscience", field: "Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 223, name: "Natural Resources", field: "Environmental Science", college: "The Polytechnic School / Wrigley (varies)", salary: "" },
    { id: 224, name: "Nursing", field: "Health/Nursing", college: "Edson College of Nursing & Health Innovation", salary: "" },
    { id: 225, name: "Nutrition and Healthy Lifestyles", field: "Health", college: "College of Health Solutions", salary: "" },
    { id: 226, name: "Operations Management", field: "Business/Operations", college: "W. P. Carey School of Business", salary: "" },
    { id: 227, name: "Organizational Leadership", field: "Business/Leadership", college: "W. P. Carey School of Business", salary: "" },
    { id: 228, name: "Philosophy", field: "Humanities", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 229, name: "Physics", field: "Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 230, name: "Planetary Science", field: "Science", college: "School of Earth and Space Exploration", salary: "" },
    { id: 231, name: "Political Science", field: "Social Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 232, name: "Psychology", field: "Social Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 233, name: "Public Affairs", field: "Public Policy", college: "Watts College of Public Service & Community Solutions", salary: "" },
    { id: 234, name: "Public Service & Public Policy", field: "Public Policy", college: "Watts College of Public Service & Community Solutions", salary: "" },
    { id: 235, name: "Recreation and Sports Business", field: "Business/Sports", college: "W. P. Carey School of Business", salary: "" },
    { id: 236, name: "Real Estate Development", field: "Business/Real Estate", college: "W. P. Carey School of Business", salary: "" },
    { id: 237, name: "Religious Studies", field: "Humanities", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 238, name: "Software Engineering", field: "Engineering/Computer", college: "Ira A. Fulton Schools of Engineering", salary: "" },
    { id: 239, name: "Sociology", field: "Social Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 240, name: "Spanish", field: "Humanities/Language", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 241, name: "Special Education", field: "Education", college: "Mary Lou Fulton Teachers College", salary: "" },
    { id: 242, name: "Sustainability", field: "Environmental Science", college: "Julie Ann Wrigley Global Institute of Sustainability", salary: "" },
    { id: 243, name: "Supply Chain Management", field: "Business/Logistics", college: "W. P. Carey School of Business", salary: "" },
    { id: 244, name: "Technical Communication", field: "Communication/Technical", college: "College of Liberal Arts and Sciences / The Polytechnic School", salary: "" },
    { id: 245, name: "Theatre", field: "Arts/Theatre", college: "Herberger Institute for Design and the Arts", salary: "" },
    { id: 246, name: "Urban Planning", field: "Design/Planning", college: "Herberger Institute for Design and the Arts / Watts College (varies)", salary: "" },
    { id: 247, name: "Visual Communication Design", field: "Design", college: "Herberger Institute for Design and the Arts", salary: "" },
    { id: 248, name: "Chinese", field: "Humanities/Language", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 249, name: "French", field: "Humanities/Language", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 250, name: "German", field: "Humanities/Language", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 251, name: "Italian", field: "Humanities/Language", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 252, name: "Japanese", field: "Humanities/Language", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 253, name: "Korean", field: "Humanities/Language", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 254, name: "Portuguese", field: "Humanities/Language", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 255, name: "Russian", field: "Humanities/Language", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 256, name: "Arabic", field: "Humanities/Language", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 257, name: "American Indian Studies", field: "Social Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 258, name: "Anthropology", field: "Social Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 259, name: "Applied Biological Sciences", field: "Science", college: "The Polytechnic School / CISA", salary: "" },
    { id: 260, name: "Applied Mathematics", field: "Mathematics", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 261, name: "Applied Physics", field: "Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 262, name: "Applied Science (Operations Management)", field: "Business/Applied Science", college: "The Polytechnic School", salary: "" },
    { id: 263, name: "Applied Science (Project Management)", field: "Business/Applied Science", college: "The Polytechnic School", salary: "" },
    { id: 264, name: "Applied Science (Software Engineering)", field: "Technology", college: "The Polytechnic School", salary: "" },
    { id: 265, name: "Applied Science (Technical Communication)", field: "Communication", college: "The Polytechnic School", salary: "" },
    { id: 266, name: "Architectural Design", field: "Design", college: "Herberger Institute for Design and the Arts", salary: "" },
    { id: 267, name: "Art Education", field: "Education/Arts", college: "Herberger Institute for Design and the Arts", salary: "" },
    { id: 268, name: "Art History", field: "Humanities", college: "Herberger Institute for Design and the Arts", salary: "" },
    { id: 269, name: "Asian Pacific American Studies", field: "Humanities/Social Sciences", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 270, name: "Biological Sciences (Biology & Society)", field: "Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 271, name: "Biological Sciences (Conservation Biology)", field: "Science/Conservation", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 272, name: "Biological Sciences (Genetics, Cell & Developmental Biology)", field: "Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 273, name: "Biological Sciences (Neurobiology, Physiology & Behavior)", field: "Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 274, name: "Biological Sciences (Biomedical Sciences)", field: "Health/Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 275, name: "Biological Sciences (Natural Science Education)", field: "Education/Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 276, name: "Biopharmaceutical Sciences", field: "Science/Health", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 277, name: "Business (Communication)", field: "Business", college: "W. P. Carey School of Business", salary: "" },
    { id: 278, name: "Business (Food Industry Management)", field: "Business", college: "W. P. Carey School of Business", salary: "" },
    { id: 279, name: "Business (Global Politics)", field: "Business/International", college: "W. P. Carey School of Business", salary: "" },
    { id: 280, name: "Business (Human Resources)", field: "Business", college: "W. P. Carey School of Business", salary: "" },
    { id: 281, name: "Business (Law)", field: "Business", college: "W. P. Carey School of Business", salary: "" },
    { id: 282, name: "Business (Sports Business)", field: "Business/Sports", college: "W. P. Carey School of Business", salary: "" },
    { id: 283, name: "Business Administration", field: "Business", college: "W. P. Carey School of Business", salary: "" },
    { id: 284, name: "Business Technology", field: "Technology/Business", college: "W. P. Carey School of Business", salary: "" },
    { id: 285, name: "Chicano/Latino Studies", field: "Humanities/Social Sciences", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 286, name: "Civic and Economic Thought and Leadership", field: "Social Science", college: "School of Civic and Economic Thought and Leadership", salary: "" },
    { id: 287, name: "Communication (Organizational Communication)", field: "Communication", college: "Hugh Downs School of Human Communication", salary: "" },
    { id: 288, name: "Computational Life Sciences", field: "Science/Computational Biology", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 289, name: "Computer Information Systems", field: "Business/Technology", college: "W. P. Carey School of Business", salary: "" },
    { id: 290, name: "Construction Engineering", field: "Engineering", college: "Ira A. Fulton Schools of Engineering", salary: "" },
    { id: 291, name: "Dance", field: "Arts/Performance", college: "Herberger Institute for Design and the Arts", salary: "" },
    { id: 292, name: "Dance Education", field: "Education/Arts", college: "Herberger Institute for Design and the Arts", salary: "" },
    { id: 293, name: "Digital Audiences", field: "Communication/Media", college: "Walter Cronkite School of Journalism and Mass Communication", salary: "" },
    { id: 294, name: "Digital Culture", field: "Arts/Technology", college: "Herberger Institute for Design and the Arts", salary: "" },
    { id: 295, name: "Earth and Environmental Studies", field: "Environmental Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 296, name: "Earth and Space Exploration (Astrobiology & Biogeosciences)", field: "Science", college: "School of Earth and Space Exploration", salary: "" },
    { id: 297, name: "Earth and Space Exploration (Geological Sciences)", field: "Science", college: "School of Earth and Space Exploration", salary: "" },
    { id: 298, name: "Earth and Space Exploration (Systems Design)", field: "Engineering/Design", college: "School of Earth and Space Exploration", salary: "" },
    { id: 299, name: "Economics (Politics and the Economy)", field: "Social Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 300, name: "Educational Studies", field: "Education", college: "Mary Lou Fulton Teachers College", salary: "" },
    { id: 301, name: "Electrical Engineering", field: "Engineering", college: "Ira A. Fulton Schools of Engineering", salary: "" },
    { id: 302, name: "Elementary Education (Bilingual Education/ESL)", field: "Education", college: "Mary Lou Fulton Teachers College", salary: "" },
    { id: 303, name: "Elementary Education (STEM emphasis)", field: "Education", college: "Mary Lou Fulton Teachers College", salary: "" },
    { id: 304, name: "Engineering Management", field: "Engineering/Management", college: "Ira A. Fulton Schools of Engineering", salary: "" },
    { id: 305, name: "Environmental Chemistry", field: "Science/Chemistry", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 306, name: "Environmental and Resource Management", field: "Environmental Science", college: "The Polytechnic School", salary: "" },
    { id: 307, name: "Environmental Studies", field: "Environmental Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 308, name: "Ethnic Studies", field: "Humanities/Social Sciences", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 309, name: "Family and Human Development", field: "Social Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 310, name: "Family and Human Development (Child Development)", field: "Social Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 311, name: "Family and Human Development (Child Psychology)", field: "Social Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 312, name: "Film (Filmmaking Practices)", field: "Arts/Film", college: "Herberger Institute for Design and the Arts", salary: "" },
    { id: 313, name: "Film (Film and Media Production)", field: "Arts/Film", college: "Herberger Institute for Design and the Arts", salary: "" },
    { id: 314, name: "Film (Film and Media Studies)", field: "Arts/Film", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 315, name: "Food Industry Management", field: "Business/Food Systems", college: "W. P. Carey School of Business", salary: "" },
    { id: 316, name: "French (Linguistics)", field: "Humanities/Language", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 317, name: "French (Literature)", field: "Humanities/Language", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 318, name: "General Studies", field: "Interdisciplinary", college: "College of Integrative Sciences and Arts (CISA)", salary: "" },
    { id: 319, name: "Geographic Information Science (GIS)", field: "Technology/GIS", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 320, name: "Global Management", field: "Business/International", college: "Thunderbird School of Global Management", salary: "" },
    { id: 321, name: "Global Studies", field: "Social Science/International", college: "School of Politics and Global Studies", salary: "" },
    { id: 322, name: "Global Technology and Development", field: "Technology/Development", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 323, name: "Graphic Information Technology", field: "Technology/Design", college: "The Polytechnic School", salary: "" },
    { id: 324, name: "Health Education and Promotion", field: "Health", college: "College of Health Solutions", salary: "" },
    { id: 325, name: "Health Sciences", field: "Health", college: "College of Health Solutions", salary: "" },
    { id: 326, name: "Health Sciences (Healthy Lifestyles Coaching)", field: "Health", college: "College of Health Solutions", salary: "" },
    { id: 327, name: "Health Sciences (Pre-Professional)", field: "Health/Pre-Professional", college: "College of Health Solutions", salary: "" },
    { id: 328, name: "History (Global History)", field: "Humanities", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 329, name: "History (U.S. History)", field: "Humanities", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 330, name: "History (World History)", field: "Humanities", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 331, name: "Human Systems Engineering", field: "Engineering/Human Systems", college: "The Polytechnic School", salary: "" },
    { id: 332, name: "Informatics", field: "Technology/Interdisciplinary", college: "School of Arts, Media and Engineering / CLA S (varies)", salary: "" },
    { id: 333, name: "Information Science", field: "Technology", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 334, name: "Integrated Digital Media", field: "Arts & Technology", college: "Herberger Institute for Design and the Arts", salary: "" },
    { id: 335, name: "Integrated Studies", field: "Interdisciplinary", college: "College of Integrative Sciences and Arts", salary: "" },
    { id: 336, name: "Interdisciplinary Arts and Performance", field: "Arts/Interdisciplinary", college: "New College of Interdisciplinary Arts and Sciences", salary: "" },
    { id: 337, name: "Interdisciplinary Studies", field: "Interdisciplinary", college: "College of Integrative Sciences and Arts", salary: "" },
    { id: 338, name: "International Letters and Cultures", field: "Humanities/Language", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 339, name: "International Trade", field: "Business/International", college: "W. P. Carey School of Business", salary: "" },
    { id: 340, name: "Italian (Literature)", field: "Humanities/Language", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 341, name: "Italian (Linguistics)", field: "Humanities/Language", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 342, name: "Japanese (Language and Culture)", field: "Humanities/Language", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 343, name: "Japanese (Literature)", field: "Humanities/Language", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 344, name: "Jewish Studies", field: "Humanities", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 345, name: "Justice Studies", field: "Social Science", college: "School of Social Transformation / Watts College", salary: "" },
    { id: 346, name: "Liberal Studies", field: "Humanities/Interdisciplinary", college: "College of Integrative Sciences and Arts", salary: "" },
    { id: 347, name: "Management", field: "Business", college: "W. P. Carey School of Business", salary: "" },
    { id: 348, name: "Management (Public Service and Public Policy)", field: "Business/Public Policy", college: "W. P. Carey School of Business / Watts College (varies)", salary: "" },
    { id: 349, name: "Marketing", field: "Business/Marketing", college: "W. P. Carey School of Business", salary: "" },
    { id: 350, name: "Mass Communication and Media Studies", field: "Communication", college: "Walter Cronkite School of Journalism and Mass Communication", salary: "" },
    { id: 351, name: "Materials Science and Engineering", field: "Engineering/Materials", college: "Ira A. Fulton Schools of Engineering", salary: "" },
    { id: 352, name: "Mathematics", field: "Mathematics", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 353, name: "Mathematics (Applied)", field: "Mathematics", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 354, name: "Mathematics (Statistics)", field: "Mathematics/Statistics", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 355, name: "Mathematics (Mathematical Biology)", field: "Mathematics/Biology", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 356, name: "Mathematics (Secondary Education)", field: "Education/Mathematics", college: "College of Liberal Arts and Sciences / Mary Lou Fulton Teachers College", salary: "" },
    { id: 357, name: "Mathematics (Actuarial Science)", field: "Mathematics/Actuarial", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 358, name: "Medical Microbiology", field: "Health/Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 359, name: "Molecular Biosciences and Biotechnology", field: "Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 360, name: "Music", field: "Arts/Music", college: "Herberger Institute for Design and the Arts", salary: "" },
    { id: 361, name: "Music (Music Theatre)", field: "Arts/Music", college: "Herberger Institute for Design and the Arts", salary: "" },
    { id: 362, name: "Music (Performance)", field: "Arts/Music Performance", college: "Herberger Institute for Design and the Arts", salary: "" },
    { id: 363, name: "Music (Theory and Composition)", field: "Arts/Music", college: "Herberger Institute for Design and the Arts", salary: "" },
    { id: 364, name: "Music (Education)", field: "Education/Music", college: "Herberger Institute for Design and the Arts / Mary Lou Fulton (varies)", salary: "" },
    { id: 365, name: "Music Therapy", field: "Health/Music Therapy", college: "Herberger Institute for Design and the Arts", salary: "" },
    { id: 366, name: "Neuroscience", field: "Science/Neuroscience", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 367, name: "Nonprofit Leadership and Management", field: "Business/Management", college: "Watts College of Public Service & Community Solutions", salary: "" },
    { id: 368, name: "Nutrition (Dietetics)", field: "Health/Nutrition", college: "College of Health Solutions", salary: "" },
    { id: 369, name: "Nutrition (Nutrition Communication)", field: "Health/Communication", college: "College of Health Solutions", salary: "" },
    { id: 370, name: "Nutrition (Nutrition Science)", field: "Health/Science", college: "College of Health Solutions", salary: "" },
    { id: 371, name: "Organizational Studies", field: "Business/Organizational", college: "W. P. Carey School of Business", salary: "" },
    { id: 372, name: "Outdoor Adventure Education", field: "Education/Outdoor", college: "College of Integrative Sciences and Arts", salary: "" },
    { id: 373, name: "Parks and Recreation Management", field: "Public Service/Education", college: "Watts College of Public Service & Community Solutions", salary: "" },
    { id: 374, name: "Performance and Movement", field: "Arts/Performance", college: "Herberger Institute for Design and the Arts", salary: "" },
    { id: 375, name: "Philosophy (Morality, Politics, and Law)", field: "Humanities", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 376, name: "Philosophy (Religion, Science and Technology)", field: "Humanities", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 377, name: "Physical Education", field: "Education/Physical", college: "College of Health Solutions", salary: "" },
    { id: 378, name: "Physics (Secondary Education)", field: "Education/Science", college: "College of Liberal Arts and Sciences / Mary Lou Fulton", salary: "" },
    { id: 379, name: "Physics (Astrophysics)", field: "Science/Astrophysics", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 380, name: "Physics (Applied Physics)", field: "Science/Applied", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 381, name: "Physics (Biophysics)", field: "Science/Biophysics", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 382, name: "Political Science (Global Politics)", field: "Social Science/International", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 383, name: "Political Science (Law and Policy)", field: "Social Science", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 384, name: "Political Science (International Relations)", field: "Social Science/International", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 385, name: "Political Science (Public Policy)", field: "Social Science/Public Policy", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 386, name: "Psychology (Forensic Psychology)", field: "Social Science/Forensic", college: "New College of Interdisciplinary Arts and Sciences", salary: "" },
    { id: 387, name: "Psychology (Health Psychology)", field: "Social Science/Health", college: "New College of Interdisciplinary Arts and Sciences", salary: "" },
    { id: 388, name: "Psychology (Human Factors)", field: "Human Factors/Engineering", college: "New College of Interdisciplinary Arts and Sciences / Fulton (varies)", salary: "" },
    { id: 389, name: "Psychology (Industrial-Organizational)", field: "Social Science/Business", college: "New College of Interdisciplinary Arts and Sciences", salary: "" },
    { id: 390, name: "Psychology (Neuroscience)", field: "Science/Neuroscience", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 391, name: "Psychology (Quantitative Methods)", field: "Mathematics/Statistics", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 392, name: "Public Health", field: "Health/Public Health", college: "College of Health Solutions", salary: "" },
    { id: 393, name: "Public Policy", field: "Public Policy", college: "College of Public Service and Community Solutions", salary: "" },
    { id: 394, name: "Real Estate", field: "Business/Real Estate", college: "W. P. Carey School of Business", salary: "" },
    { id: 395, name: "Religious Studies", field: "Humanities", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 396, name: "Religious Studies (Religion, Culture & Public Life)", field: "Humanities", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 397, name: "Religious Studies (Religion & International Affairs)", field: "Humanities/International", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 398, name: "Religious Studies (Religion & Psychology)", field: "Humanities/Psychology", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 399, name: "Religious Studies (Religion, Politics & Global Affairs)", field: "Humanities/Politics", college: "College of Liberal Arts and Sciences", salary: "" },
    { id: 400, name: "Secondary Education (English)", field: "Education", college: "Mary Lou Fulton Teachers College", salary: "" },
    { id: 401, name: "Secondary Education (History)", field: "Education", college: "Mary Lou Fulton Teachers College", salary: "" },
    { id: 402, name: "Secondary Education (Mathematics)", field: "Education", college: "Mary Lou Fulton Teachers College", salary: "" }
];


